# Single Dimension NumPy array

In [1]:
!dir


 Volume in drive E is my_domain
 Volume Serial Number is 7A3D-1185

 Directory of E:\Data_science

09/06/2025  15:37    <DIR>          .
30/05/2025  20:34    <DIR>          .ipynb_checkpoints
03/06/2025  17:11                 0 a.py
29/05/2025  08:20    <DIR>          anaconda_projects
28/05/2025  21:47             1,491 Assignment.py
09/06/2025  15:31             1,730 math.py
27/05/2025  14:49             2,231 new.py
30/05/2025  15:59             3,005 One.py
03/06/2025  16:45                99 pattern.py
01/06/2025  06:44                 8 README.md
03/06/2025  16:28               428 test.py
28/05/2025  16:30               252 try.cpp
30/05/2025  17:41             1,638 Two.py
01/06/2025  06:58             1,989 Two1.py
27/05/2025  16:48            24,379 Untitled.ipynb
30/05/2025  20:35             5,417 Untitled1.ipynb
09/06/2025  15:37               337 Untitled2.ipynb
              14 File(s)         43,004 bytes
               3 Dir(s)  195,884,654,592 bytes free


In [3]:
!pip install numpy


In [4]:
import numpy as np

In [15]:
import numpy as np
n2=np.array([10,2.0,2+3j,True]) #we cannot use different datatypes in numpy array
n2

array([10.+0.j,  2.+0.j,  2.+3.j,  1.+0.j])

In [11]:
import numpy as np
n1=np.array([10,20,30,40]) 
n1

array([10, 20, 30, 40])

type(n1)

# MultiDimensional Array

In [21]:
import numpy as np
n3=np.array([[10,20,30],[30,40,50],[40,50,60]])
print(n3)

[[10 20 30]
 [30 40 50]
 [40 50 60]]


In [19]:
n3.shape

(3, 3)

# initialize numpy array with zeros

In [26]:
n4=np.zeros((9,9))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# initial array matrix with full then

In [36]:
n4=np.full((3,3),9)
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# full range

In [32]:
n5=np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# initialization of numpy arrays with skip numbers

In [35]:
n6=np.arange(1,10,2 ) #odd numbers
n6

array([1, 3, 5, 7, 9])

# initialization of numpy array with the random numbers

In [40]:
n7=np.random.randint(100,1000,10)
n7

array([316, 372, 123, 882, 128, 765, 831, 800, 639, 278])

# initialization the array shape changes in a fraction of seconds

In [43]:
n8=np.array([[10,20,30],[30,40,50],[60,70,80],[90,60,50]])
n8

array([[10, 20, 30],
       [30, 40, 50],
       [60, 70, 80],
       [90, 60, 50]])

In [44]:
n8.shape

(4, 3)

In [46]:
n8.shape=(3,4)
n8

array([[10, 20, 30, 30],
       [40, 50, 60, 70],
       [80, 90, 60, 50]])

# joining the numpy array

In [55]:
a=np.array([10,20,30,4,5,6,7,8,9,12])
b=np.array([1,2,3,4,5,6,7,9,12])

In [48]:
np.vstack((a,b)) # joining the numpy as vertical section

array([[10, 20, 30,  4,  5,  6,  7,  8,  9, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12]])

In [49]:
np.hstack((a,b)) # joining the numpy as horizontal section

array([10, 20, 30,  4,  5,  6,  7,  8,  9, 12,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 12])

In [56]:
np.column_stack((a,b)) #joining the numpy as column

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10 and the array at index 1 has size 9

# numpy intersection and difference

In [58]:
x=np.array([1,4,6,7,8,9,12])
y=np.array([1,4,5,6,7,8,12])


In [59]:
np.intersect1d(x,y)

array([ 1,  4,  6,  7,  8, 12])

In [60]:
np.setdiff1d(x,y)

array([9])

# addition of numpy arrays

In [66]:
t=np.array([10,20])
s=np.array([10,2])

In [67]:
np.sum([t,s])

42

In [76]:
np.sum([t,s],axis = 1)# columnaddition

array([30, 12])

In [73]:
np.sum([t,s],axis = 0)# row addition

array([20, 22])

# NUmpy array of mathematics

In [74]:
p=np.array([10,20,30])

In [75]:
p+1

array([11, 21, 31])

In [77]:
p-1

array([ 9, 19, 29])

In [78]:
p*2

array([20, 40, 60])

In [79]:
p*3

array([30, 60, 90])

In [80]:
p/4

array([2.5, 5. , 7.5])

# numpy maths of functions

In [126]:
import numpy as np
nn=np.array([10,20,10,30])

In [127]:
np.mean(nn)

17.5

In [128]:
np.median(nn)

15.0

In [129]:
np.std(nn)

8.2915619758885

In [130]:
np.var(nn)

68.75

In [131]:
np.max(nn)

30

In [132]:
np.percentile(nn,75)

22.5

In [133]:
np.average(nn)

17.5

In [110]:
np.cov(nn)

array(166.66666667)

In [111]:
np.mean(nn)

25.0

In [112]:
np.std(nn)

11.180339887498949

In [134]:
from scipy import stats
stats.mode(nn)

ModeResult(mode=10, count=2)

# saving and loading NUmpy array

In [118]:
import numpy as np
n11=np.array([10,20,30])
n11

array([10, 20, 30])

In [119]:
np.save('my_name',n11) #saving the numpy array

In [120]:
np.load('my_name.npy') #loading the numpy array

array([10, 20, 30])

In [135]:
!pip install graphviz

In [136]:
!pip install dask

In [137]:
!pip install pandas

In [ ]:
!pip install pyspark

In [1]:
!git init


Reinitialized existing Git repository in E:/Data_science/.git/


In [2]:
!git remote add origin https://github.com/ANOT-coder/Data_science-Repo.git


error: remote origin already exists.


In [4]:
!git pull origin main


Already up to date.


From https://github.com/ANOT-coder/Python
 * branch            main       -> FETCH_HEAD


In [5]:
! git add .


In [6]:
!git status


On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .ipynb_checkpoints/Day1(data_science)-checkpoint.ipynb
	new file:   Day1(data_science).ipynb
	modified:   Two1.py
	new file:   a.py
	new file:   math.py
	new file:   my_name.npy
	new file:   pattern.py
	new file:   test.py

