# Single Dimension NumPy array

In [1]:
!dir


 Volume in drive E is my_domain
 Volume Serial Number is 7A3D-1185

 Directory of E:\Data_science

09/06/2025  15:37    <DIR>          .
30/05/2025  20:34    <DIR>          .ipynb_checkpoints
03/06/2025  17:11                 0 a.py
29/05/2025  08:20    <DIR>          anaconda_projects
28/05/2025  21:47             1,491 Assignment.py
09/06/2025  15:31             1,730 math.py
27/05/2025  14:49             2,231 new.py
30/05/2025  15:59             3,005 One.py
03/06/2025  16:45                99 pattern.py
01/06/2025  06:44                 8 README.md
03/06/2025  16:28               428 test.py
28/05/2025  16:30               252 try.cpp
30/05/2025  17:41             1,638 Two.py
01/06/2025  06:58             1,989 Two1.py
27/05/2025  16:48            24,379 Untitled.ipynb
30/05/2025  20:35             5,417 Untitled1.ipynb
09/06/2025  15:37               337 Untitled2.ipynb
              14 File(s)         43,004 bytes
               3 Dir(s)  195,884,654,592 bytes free


In [3]:
!pip install numpy


In [4]:
import numpy as np

In [15]:
import numpy as np
n2=np.array([10,2.0,2+3j,True]) #we cannot use different datatypes in numpy array
n2

array([10.+0.j,  2.+0.j,  2.+3.j,  1.+0.j])

In [11]:
import numpy as np
n1=np.array([10,20,30,40]) 
n1

array([10, 20, 30, 40])

type(n1)

# MultiDimensional Array

In [21]:
import numpy as np
n3=np.array([[10,20,30],[30,40,50],[40,50,60]])
print(n3)

[[10 20 30]
 [30 40 50]
 [40 50 60]]


In [19]:
n3.shape

(3, 3)

# initialize numpy array with zeros

In [26]:
n4=np.zeros((9,9))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# initial array matrix with full then

In [36]:
n4=np.full((3,3),9)
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# full range

In [32]:
n5=np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# initialization of numpy arrays with skip numbers

In [35]:
n6=np.arange(1,10,2 ) #odd numbers
n6

array([1, 3, 5, 7, 9])

# initialization of numpy array with the random numbers

In [40]:
n7=np.random.randint(100,1000,10)
n7

array([316, 372, 123, 882, 128, 765, 831, 800, 639, 278])

# initialization the array shape changes in a fraction of seconds

In [43]:
n8=np.array([[10,20,30],[30,40,50],[60,70,80],[90,60,50]])
n8

array([[10, 20, 30],
       [30, 40, 50],
       [60, 70, 80],
       [90, 60, 50]])

In [44]:
n8.shape

(4, 3)

In [46]:
n8.shape=(3,4)
n8

array([[10, 20, 30, 30],
       [40, 50, 60, 70],
       [80, 90, 60, 50]])

# joining the numpy array

In [55]:
a=np.array([10,20,30,4,5,6,7,8,9,12])
b=np.array([1,2,3,4,5,6,7,9,12])

In [48]:
np.vstack((a,b)) # joining the numpy as vertical section

array([[10, 20, 30,  4,  5,  6,  7,  8,  9, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12]])

In [49]:
np.hstack((a,b)) # joining the numpy as horizontal section

array([10, 20, 30,  4,  5,  6,  7,  8,  9, 12,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 12])

In [56]:
np.column_stack((a,b)) #joining the numpy as column

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10 and the array at index 1 has size 9

# numpy intersection and difference

In [58]:
x=np.array([1,4,6,7,8,9,12])
y=np.array([1,4,5,6,7,8,12])


In [59]:
np.intersect1d(x,y)

array([ 1,  4,  6,  7,  8, 12])

In [60]:
np.setdiff1d(x,y)

array([9])

# addition of numpy arrays

In [66]:
t=np.array([10,20])
s=np.array([10,2])

In [67]:
np.sum([t,s])

42

In [76]:
np.sum([t,s],axis = 1)# columnaddition

array([30, 12])

In [73]:
np.sum([t,s],axis = 0)# row addition

array([20, 22])

# NUmpy array of mathematics

In [74]:
p=np.array([10,20,30])

In [75]:
p+1

array([11, 21, 31])

In [77]:
p-1

array([ 9, 19, 29])

In [78]:
p*2

array([20, 40, 60])

In [79]:
p*3

array([30, 60, 90])

In [80]:
p/4

array([2.5, 5. , 7.5])

# numpy maths of functions

In [126]:
import numpy as np
nn=np.array([10,20,10,30])

In [127]:
np.mean(nn)

17.5

In [128]:
np.median(nn)

15.0

In [129]:
np.std(nn)

8.2915619758885

In [130]:
np.var(nn)

68.75

In [131]:
np.max(nn)

30

In [132]:
np.percentile(nn,75)

22.5

In [133]:
np.average(nn)

17.5

In [110]:
np.cov(nn)

array(166.66666667)

In [111]:
np.mean(nn)

25.0

In [112]:
np.std(nn)

11.180339887498949

In [134]:
from scipy import stats
stats.mode(nn)

ModeResult(mode=10, count=2)

# saving and loading NUmpy array

In [118]:
import numpy as np
n11=np.array([10,20,30])
n11

array([10, 20, 30])

In [119]:
np.save('my_name',n11) #saving the numpy array

In [120]:
np.load('my_name.npy') #loading the numpy array

array([10, 20, 30])

In [135]:
!pip install graphviz

In [136]:
!pip install dask

In [137]:
!pip install pandas

In [ ]:
!pip install pyspark

In [1]:
!git init


Reinitialized existing Git repository in E:/Data_science/.git/


In [2]:
!git remote add origin https://github.com/ANOT-coder/Data_science-Repo.git


error: remote origin already exists.


In [4]:
!git pull origin main


Already up to date.


From https://github.com/ANOT-coder/Python
 * branch            main       -> FETCH_HEAD


In [5]:
! git add .


In [6]:
!git status


On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .ipynb_checkpoints/Day1(data_science)-checkpoint.ipynb
	new file:   Day1(data_science).ipynb
	modified:   Two1.py
	new file:   a.py
	new file:   math.py
	new file:   my_name.npy
	new file:   pattern.py
	new file:   test.py



In [7]:
! git add Day1(data_science).ipynb

In [9]:
!git status


On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .ipynb_checkpoints/Day1(data_science)-checkpoint.ipynb
	new file:   Day1(data_science).ipynb
	modified:   Two1.py
	new file:   a.py
	new file:   math.py
	new file:   my_name.npy
	new file:   pattern.py
	new file:   test.py



In [10]:
!git commit -m "Day1"

[main 524b63d] Day1
 8 files changed, 2043 insertions(+), 7 deletions(-)
 create mode 100644 .ipynb_checkpoints/Day1(data_science)-checkpoint.ipynb
 create mode 100644 Day1(data_science).ipynb
 create mode 100644 a.py
 create mode 100644 math.py
 create mode 100644 my_name.npy
 create mode 100644 pattern.py
 create mode 100644 test.py


In [ ]:
! git push origin main


# array creation

#uniform samples

In [9]:
import numpy as np
np.random.uniform(5,10,size = 4) # used for otp generation

array([9.72067152, 9.77327783, 9.0947146 , 8.88854627])

In [ ]:
np.random.uniform(size=5)

In [6]:
np.random.uniform(size=(2,3))

array([[0.09338737, 0.22544702, 0.91046458],
       [0.60603449, 0.94031867, 0.20295212]])

#logspace

In [8]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

In [10]:
#identity

In [11]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
a=np.array([-0.1,-0.2,0.5,1,1.5,1.4,1.9,2.3,4.5])
bins=np.array([1,2,3,4])
np.digitize(a,bins)

array([0, 0, 0, 1, 1, 1, 1, 2, 4], dtype=int64)

#expand dimensions

In [15]:
arr=np.array([8,14,5,6,7,8,9,7])
np.expand_dims(arr,axis=0)

array([[ 8, 14,  5,  6,  7,  8,  9,  7]])

In [17]:
np.expand_dims(arr,axis=1)

array([[ 8],
       [14],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 7]])

#squeeze 

In [20]:
arr=np.array([[8],[14],[15],[11]])
np.squeeze(arr)

array([ 8, 14, 15, 11])

In [28]:
a=np.array([0,0,1,1,1.5])
np.count_nonzero(a)
abs(len(a))-np.count_nonzero(a)#non zero element


2

In [30]:
arr=np.array([1,2,56,7,9,8])
np.sort(arr)

array([ 1,  2,  7,  8,  9, 56])

In [31]:
#abs
A=np.array([-1,-2,-5,4])
np.abs(A)

array([1, 2, 5, 4])

In [32]:
a=np.random.random(size=(3,4))
a

array([[0.17731472, 0.07510131, 0.33257981, 0.82793617],
       [0.47863223, 0.29443885, 0.64622103, 0.35290386],
       [0.93247408, 0.14764044, 0.11840569, 0.22867475]])

In [34]:
np.round(a,decimals=0)

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [35]:
np.round(a,decimals=1)

array([[0.2, 0.1, 0.3, 0.8],
       [0.5, 0.3, 0.6, 0.4],
       [0.9, 0.1, 0.1, 0.2]])

In [38]:
arr=np.array([0,2,3,45,8,9,90,5,6])
arr.clip(0,5)#certain range ko value dinxa 

array([0, 2, 3, 5, 5, 5, 5, 5, 5])

In [39]:
arr.clip(1,100)

array([ 1,  2,  3, 45,  8,  9, 90,  5,  6])

In [42]:
#copyto
import numpy as np
arr1=np.array([2,4,5])
arr2=np.array([1,3,6])
print("before:",arr1)
print("before:",arr2)
np.copyto(arr1,arr2)
print("after:",arr1)
print("after:",arr2)

before: [2 4 5]
before: [1 3 6]
after: [1 3 6]
after: [1 3 6]


In [62]:
a1=np.array([[1,2,3],[4,5,6],[5,6,7]])
b1=np.array([[1,4,3],[3,2,3],[7,8,9]])

In [63]:
np.einsum('ji',a1)# transpose


array([[1, 4, 5],
       [2, 5, 6],
       [3, 6, 7]])

In [64]:
import numpy as np
np.einsum('ij , jk',a1,b1)#matrix multiplication

array([[28, 32, 36],
       [61, 74, 81],
       [72, 88, 96]])

In [65]:
np.einsum('ii',a1)

13

In [78]:
x=np.array([[2,3],[3,4]])
np.linalg.det(x)


-1.0000000000000004

In [77]:
np.linalg.inv(x)

array([[-4.,  3.],
       [ 3., -2.]])

In [81]:
#vector
import numpy as np
#1. basic summation
a=np.array([1,2,3])
print(np.einsum('i->',a)) #sum over all elements


      

6


In [82]:
#2 element wuse multiplication and summation
a=np.array([1,2,3])
b=np.array([1,2,2])
print(np.einsum('i,i->',a,b))

11


In [83]:
#3 outer product
a=np.array([1,2,3])
b=np.array([1,2,2])
print(np.einsum('i,j->ij',a,b))

[[1 2 2]
 [2 4 4]
 [3 6 6]]


In [84]:
#4 matrix transposition
a=np.array([[1,2,3],[1,2,2]])
print(np.einsum('ij->ji',a))

[[1 1]
 [2 2]
 [3 2]]


In [89]:
#5 matrix vector multiplication
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([7,8])
print(np.einsum('ij,j->i',a,b))


[23 53 83]


In [88]:
#6 matrix multiplication
a=np.array([[1,2],[1,2]])
b=np.array([[1,2],[4,5]])
print(np.einsum('ij,jk->jk',a,b))


[[ 2  4]
 [16 20]]


In [91]:
#7 Trace of a matrix
a=np.array([[1,2],[3,4]])
print(np.einsum('ii->',a))
      

5


In [95]:
#array printing options)
np.set_printoptions(precision=2)
a=np.array([12.3464,34.5346])
print(a)

[12.35 34.53]


In [99]:
#prints array to its max
np.set_printoptions(threshold=np.inf)


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,3,2],[3,2,1],[9,8,7]])
print.